#!/usr/bin/env sh

# clean old temporal database
npm run test:clean

# create new temporal database
createdb domain-container-test

# create table
node test/create-table.js

# run tests
mocha test/domain-container.js
